"""init

Revision ID: 9e5379dac196
Revises: 
Create Date: 2024-10-19 14:22:07.937479

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9e5379dac196"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", sa.Text(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("type", sa.Text(), nullable=False, comment="Task type"),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Result of the task execution"),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Parameter of the task execution"
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error message of the task execution"),
        sa.Column("error_code", sa.Integer(), nullable=True, comment="Error Code of the task execution"),
        sa.Column("status", sa.Text(), server_default=sa.text("'QUEUED'"), nullable=False, comment="The task status"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The time when the task was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="The time when the task was updated",
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True, comment="The time when the task was started"),
        sa.Column("ended_at", sa.DateTime(), nullable=True, comment="The time when the task was ended"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_created_at"), "task", ["created_at"], unique=False)
    op.create_index(op.f("ix_task_status"), "task", ["status"], unique=False)
    op.create_index(op.f("ix_task_type"), "task", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_type"), table_name="task")
    op.drop_index(op.f("ix_task_status"), table_name="task")
    op.drop_index(op.f("ix_task_created_at"), table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###
