version: "3"
name: services
services:
  redis_server:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: always
  postgres_server:
    image: postgres:12.15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xxx
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod", "-U", "postgres"]
      interval: 10s
      timeout: 60s
      retries: 3
  task-processing-system-api-server:
    image: task-processing-system
    environment:
      DO_INIT_DB: "true"
      POSTGRES_HOST: postgres_server
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "xxx"
      POSTGRES_DB: "task-processing-system-dev"
      REDIS_HOST: redis_server
      REDIS_PORT: "6379"
      BACKEND_CORS_ORIGINS: "http://localhost:8000"
      PORT: "8000"
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 10s
    depends_on:
      postgres_server:
        condition: service_healthy
  task-processing-system-api-server-worker:
    image: task-processing-system-worker
    environment:
      DO_INIT_DB: "true"
      POSTGRES_HOST: postgres_server
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "xxx"
      POSTGRES_DB: "task-processing-system-dev"
      REDIS_HOST: redis_server
      REDIS_PORT: "6379"
      BACKEND_CORS_ORIGINS: "http://localhost:8000"
      PORT: "8000"
    restart: always
    depends_on:
      postgres_server:
        condition: service_healthy
volumes:
  pgdata:
    external: true
