FROM python:3.8-slim-buster

ENV PYTHONPATH "${PYTHONPATH}:/"

RUN pip install --upgrade pip

COPY ./requirements.txt /app/
COPY ./app /app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "worker_main.py"]