FROM python:3.8-slim-buster

ENV PRIVATE_PYPI_URL=http://172.31.69.231:80
ENV PRIVATE_PYPI_DOMAIN=172.31.69.231

WORKDIR /home/worker
COPY . /home/worker

RUN pip install --extra-index-url ${PRIVATE_PYPI_URL} --trusted-host ${PRIVATE_PYPI_DOMAIN} --no-cache-dir -r requirements.txt -U

WORKDIR /home/worker

ENV PYTHONPATH=/home/worker

CMD ["python3", "/home/worker/app/worker/main.py"]